import React, { useState } from 'react';
import { UserProfile, TimelineItem, ChatMessage } from '../types';
import { FileText, Printer, Copy, Check, X, Stethoscope, Calendar, HeartPulse, ShieldAlert, Pill, HelpCircle } from 'lucide-react';

interface DoctorSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  profile: UserProfile;
  timeline: TimelineItem[];
  messages: ChatMessage[];
}

export const DoctorSummaryModal: React.FC<DoctorSummaryModalProps> = ({
  isOpen,
  onClose,
  profile,
  timeline,
  messages,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateTextSummary = () => {
    let text = `=========================================\n`;
    text += `DOCTOR VISIT HEALTH SUMMARY\n`;
    text += `Generated by Aura Health Copilot\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n`;
    text += `=========================================\n\n`;

    text += `PATIENT INFORMATION:\n`;
    text += `- Name: ${profile.name}\n`;
    text += `- Age: ${profile.age || 'N/A'}\n`;
    text += `- Gender: ${profile.gender || 'N/A'}\n`;
    text += `- Blood Type: ${profile.bloodType || 'N/A'}\n`;
    text += `- Allergies: ${profile.allergies.length ? profile.allergies.join(', ') : 'None listed'}\n`;
    text += `- Known Conditions: ${profile.existingConditions.length ? profile.existingConditions.join(', ') : 'None'}\n`;
    text += `- Medications: ${profile.medications.length ? profile.medications.join(', ') : 'None'}\n\n`;

    text += `CURRENT SYMPTOMS & HEALTH TIMELINE:\n`;
    if (timeline.length === 0) {
      text += `No logged timeline items.\n\n`;
    } else {
      timeline.forEach((item, idx) => {
        text += `${idx + 1}. ${item.symptom} (${item.dateFormatted}) - Risk Level: ${item.riskLevel.toUpperCase()} [Status: ${item.status}]\n   Notes: ${item.details}\n`;
      });
      text += `\n`;
    }

    text += `QUESTIONS TO ASK MY DOCTOR:\n`;
    text += `1. What potential underlying causes should we test for based on these symptoms?\n`;
    text += `2. Are there any prescription or lifestyle adjustments recommended for my profile?\n`;
    text += `3. Which red flag symptoms should prompt me to go to Urgent Care?\n\n`;

    text += `-----------------------------------------\n`;
    text += `Note: This summary is compiled from patient-entered logs and AI health copilot notes. It is intended to facilitate conversation with your healthcare provider.\n`;

    return text;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateTextSummary());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-xl z-50 flex items-center justify-center p-4 overflow-y-auto">
      <div className="glass-panel rounded-3xl max-w-2xl w-full p-6 sm:p-8 shadow-[0_20px_60px_rgba(0,0,0,0.6)] border border-white/20 bg-slate-900/90 my-8 relative text-white space-y-6">
        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-purple-500/20 text-purple-300 flex items-center justify-center border border-purple-400/30">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Doctor Visit Health Summary</h2>
              <p className="text-xs text-slate-300">
                Formatted patient summary ready to print or bring to your appointment
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-2 rounded-full bg-white/5 hover:bg-white/15 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Printable Area */}
        <div className="space-y-6 text-slate-200 text-xs leading-relaxed bg-black/40 p-6 rounded-2xl border border-white/10">
          {/* Header */}
          <div className="flex justify-between items-start border-b border-white/10 pb-4">
            <div>
              <div className="flex items-center gap-2">
                <Stethoscope className="w-4 h-4 text-purple-400" />
                <span className="font-bold text-white text-sm">Aura Patient Summary</span>
              </div>
              <p className="text-[11px] text-slate-400 mt-0.5">Prepared for Physician / Urgent Care Consultation</p>
            </div>
            <div className="text-right text-[11px] text-slate-400">
              <span className="flex items-center gap-1 justify-end font-medium text-slate-300">
                <Calendar className="w-3 h-3 text-purple-400" />
                {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
              </span>
            </div>
          </div>

          {/* Patient Details */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-white/5 p-3.5 rounded-xl border border-white/10">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-400 block">Patient</span>
              <span className="font-semibold text-white">{profile.name}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-400 block">Age / Gender</span>
              <span className="font-semibold text-white">{profile.age || 'N/A'} yrs • {profile.gender}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-400 block">Allergies</span>
              <span className="font-semibold text-amber-300">{profile.allergies.join(', ') || 'None'}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-400 block">Conditions</span>
              <span className="font-semibold text-white">{profile.existingConditions.join(', ') || 'None'}</span>
            </div>
          </div>

          {/* Timeline / Symptoms */}
          <div>
            <h3 className="font-bold text-white text-xs mb-2 flex items-center gap-1.5 uppercase tracking-wider">
              <HeartPulse className="w-3.5 h-3.5 text-teal-400" />
              Symptom Log & History
            </h3>
            {timeline.length > 0 ? (
              <div className="space-y-2">
                {timeline.map((item) => (
                  <div key={item.id} className="bg-white/5 p-3 rounded-xl border border-white/10 flex justify-between items-start gap-2">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-white">{item.symptom}</span>
                        <span className={`px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase ${
                          item.riskLevel === 'see_doctor'
                            ? 'bg-rose-500/20 text-rose-300'
                            : item.riskLevel === 'monitor'
                            ? 'bg-amber-500/20 text-amber-300'
                            : 'bg-emerald-500/20 text-emerald-300'
                        }`}>
                          {item.riskLevel}
                        </span>
                      </div>
                      <p className="text-slate-300 text-[11px] mt-1">{item.details}</p>
                    </div>
                    <span className="text-[10px] text-slate-400 shrink-0 font-medium">{item.dateFormatted}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-slate-400 italic bg-white/5 p-3 rounded-xl border border-white/10">No logged symptoms in timeline.</p>
            )}
          </div>

          {/* Suggested Physician Questions */}
          <div>
            <h3 className="font-bold text-white text-xs mb-2 flex items-center gap-1.5 uppercase tracking-wider">
              <HelpCircle className="w-3.5 h-3.5 text-sky-400" />
              Suggested Questions for Your Doctor
            </h3>
            <ul className="bg-white/5 p-3.5 rounded-xl border border-white/10 space-y-1.5 list-disc pl-5 text-slate-300">
              <li>Are my current symptoms connected to my existing medical context or allergies?</li>
              <li>What diagnostic tests or bloodwork would you recommend at this stage?</li>
              <li>Which red flag symptoms should prompt me to seek immediate emergency care?</li>
            </ul>
          </div>
        </div>

        {/* Modal Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-4 border-t border-white/10">
          <p className="text-[11px] text-slate-400">
            Aura Health Copilot report sheet
          </p>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              onClick={handleCopy}
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-4 py-2 bg-white/10 hover:bg-white/20 text-slate-200 font-semibold rounded-xl text-xs transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Text' : 'Copy Summary'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-4 py-2 glass-button-glow text-white font-semibold rounded-xl text-xs transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
