import { QuickPrompt, TimelineItem, UserProfile, HealthMetricPoint } from './types';

export const INITIAL_HEALTH_METRIC_POINTS: HealthMetricPoint[] = [
  {
    id: 'm-1',
    date: 'Aug 05',
    timestamp: Date.now() - 7 * 86400000,
    heartRate: 72,
    restingHeartRate: 64,
    temperature: 98.4,
    systolic: 118,
    diastolic: 78,
    spO2: 98,
    readinessScore: 85,
  },
  {
    id: 'm-2',
    date: 'Aug 06',
    timestamp: Date.now() - 6 * 86400000,
    heartRate: 74,
    restingHeartRate: 65,
    temperature: 98.6,
    systolic: 120,
    diastolic: 80,
    spO2: 99,
    readinessScore: 82,
  },
  {
    id: 'm-3',
    date: 'Aug 07',
    timestamp: Date.now() - 5 * 86400000,
    heartRate: 82,
    restingHeartRate: 69,
    temperature: 99.4,
    systolic: 126,
    diastolic: 83,
    spO2: 97,
    readinessScore: 75,
    notes: 'Noticed scratchy throat and slight fatigue',
  },
  {
    id: 'm-4',
    date: 'Aug 08',
    timestamp: Date.now() - 4 * 86400000,
    heartRate: 88,
    restingHeartRate: 73,
    temperature: 100.2,
    systolic: 130,
    diastolic: 85,
    spO2: 96,
    readinessScore: 68,
    notes: 'Low fever recorded in afternoon. Drank extra hydration.',
  },
  {
    id: 'm-5',
    date: 'Aug 09',
    timestamp: Date.now() - 3 * 86400000,
    heartRate: 79,
    restingHeartRate: 68,
    temperature: 98.9,
    systolic: 122,
    diastolic: 81,
    spO2: 98,
    readinessScore: 78,
  },
  {
    id: 'm-6',
    date: 'Aug 10',
    timestamp: Date.now() - 2 * 86400000,
    heartRate: 71,
    restingHeartRate: 63,
    temperature: 98.6,
    systolic: 118,
    diastolic: 77,
    spO2: 99,
    readinessScore: 88,
  },
  {
    id: 'm-7',
    date: 'Aug 11',
    timestamp: Date.now() - 1 * 86400000,
    heartRate: 68,
    restingHeartRate: 62,
    temperature: 98.4,
    systolic: 116,
    diastolic: 76,
    spO2: 99,
    readinessScore: 92,
  },
  {
    id: 'm-8',
    date: 'Aug 12',
    timestamp: Date.now(),
    heartRate: 67,
    restingHeartRate: 61,
    temperature: 98.3,
    systolic: 115,
    diastolic: 75,
    spO2: 99,
    readinessScore: 95,
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Alex Morgan',
  age: 34,
  gender: 'Female',
  existingConditions: ['Mild Asthma', 'Seasonal Allergies'],
  allergies: ['Penicillin', 'Dust Mites'],
  medications: ['Albuterol Inhaler (as needed)'],
  notes: 'Prefers non-drowsy remedies when possible. Exercises 3x a week.',
  theme: 'deep-space',
};

export const SAMPLE_QUICK_PROMPTS: QuickPrompt[] = [
  {
    id: '0',
    title: 'How am I doing today?',
    subtitle: 'Compare today’s vitals & history',
    query: 'How am I doing today? Compare my current heart rate and temperature against my historical data.',
    category: 'wellness',
    icon: 'Activity',
  },
  {
    id: '1',
    title: 'Persistent Headache',
    subtitle: 'Dull ache for 2 days',
    query: 'I have had a dull, throbbing headache behind my eyes for 2 days. It gets slightly worse in the afternoon.',
    category: 'common',
    icon: 'Brain',
  },
  {
    id: '2',
    title: 'Sore Throat & Fatigue',
    subtitle: 'Mild fever & scratchy throat',
    query: 'I woke up with a scratchy sore throat, feeling very tired and slightly chilly. No severe breathing trouble.',
    category: 'common',
    icon: 'Thermometer',
  },
  {
    id: '3',
    title: 'Chest Tightness Question',
    subtitle: 'When to seek Urgent Care',
    query: 'What are the red flag symptoms for chest tightness or pressure that mean I should go to emergency or see a doctor immediately?',
    category: 'urgent',
    icon: 'HeartPulse',
  },
  {
    id: '4',
    title: 'Stomach Cramps after Eating',
    subtitle: 'Bloating & mild nausea',
    query: 'I have had mild stomach cramps and bloating after meals since yesterday. No vomiting.',
    category: 'tracking',
    icon: 'Activity',
  },
  {
    id: '5',
    title: 'Sleep & Energy Tips',
    subtitle: 'Waking up unrefreshed',
    query: 'I have been sleeping 7 hours but waking up feeling unrefreshed and foggy. What could cause this?',
    category: 'wellness',
    icon: 'Moon',
  },
];

export const INITIAL_TIMELINE_ITEMS: TimelineItem[] = [
  {
    id: 'tl-1',
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000, // 3 days ago
    dateFormatted: '3 days ago',
    symptom: 'Frontal Headache',
    riskLevel: 'low',
    details: 'Mild pressure behind forehead after long screen time. Resolved with rest and hydration.',
    status: 'resolved',
  },
  {
    id: 'tl-2',
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000, // Yesterday
    dateFormatted: 'Yesterday',
    symptom: 'Mild Fatigue',
    riskLevel: 'monitor',
    details: 'Sluggish afternoon energy. Noted slight scratchiness in throat in evening.',
    status: 'monitoring',
  },
];
